apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smollm2/app.yaml
  - namespaces.yaml
  - observability.yaml
  - governance.yaml
  - governance-policies.yaml
  - security.yaml