apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smollm2/app.yaml
  - observability/base/kustomization.yaml
  - governance/base/kustomization.yaml
  - security/base/kustomization.yaml